name: Go

on:
- push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Build kurun binary
      run: go build -v .

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Run kurun tests
      run: go test ./...

    - name: Run tunnel tests
      run: go test ./...
      working-directory: ./tunnel

