name: Server Image

on:
  push:
    branches:
      - master
    tags:
      - server-v[0-9].[0-9].[0-9]+
env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Determine tag or commit
        uses: haya14busa/action-cond@v1
        id: refortag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: latest
      - name: Determine image tag
        id: imagetag
        run: echo "::set-output name=value::$(echo ${TAG_OR_BRANCH##*/}| sed 's/server-//g')"
        env:
          TAG_OR_BRANCH: ${{ steps.refortag.outputs.value }}
      - name: Path from tag
        id: pathfromtag
        run: echo "::set-output name=value::$(echo $TAG | sed -E 's/^(v[0-9]+\.v[0-9]+\.[0-9]+).*/\1/')"
        env:
          TAG: ${{ steps.imagetag.outputs.value }}
      - name: Build Server
        uses: docker/build-push-action@v2
        with:
          context: tunnel/
          tags: ghcr.io/banzaicloud/kurun-server:${{ steps.pathfromtag.outputs.value }}
          file: tunnel/Dockerfile.server
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache


