name: Server image

on:
  push:
    branches:
    - master
    tags:
    - server-v[0-9]+.[0-9]+.[0-9]+*
env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Determine image tag
        id: imagetag
        run: echo "::set-output name=value::$(if [ $REF_TYPE = tag ]; then echo $REF_NAME | sed 's/server-//g'; elif [ $REF_NAME = master ]; then echo latest; else echo $REF_NAME; fi)"
        env:
          REF_NAME: ${{ github.ref_name }}
          REF_TYPE: ${{ github.ref_type }}
      - name: Build kurun-server image
        uses: docker/build-push-action@v2
        with:
          context: tunnel/
          tags: ghcr.io/banzaicloud/kurun-server:${{ steps.imagetag.outputs.value }}
          file: tunnel/Dockerfile.server
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache


